### ISSUE TITLE
Runoff is currently disabled

### ISSUE THREAD

**Issue by angus-g** [COSIMA/mom6-eac#2]
See here: https://github.com/COSIMA/mom6-eac/blob/d620cf8f59e732b60cda02167c59e1d750924113/data_table#L16

I think we needed to do some kind of runoff remapping on mom6-panan, because otherwise the "nearest" interpolation referencing the full file dumps the global runoff not captured in the domain somewhere on the boundary.

**Comment by AndyHoggANU** [comment]
OK, so there is a `regrid_runoff` directory which we used to crop runoff for panant — maybe we need to apply that cropping to the EAC domain??

**Comment by angus-g** [comment]
Ah, that's right! I had forgotten what we did there. Yep, I think we need to do that cropping on the EAC domain (and store the process in our `scripts` directory for reproducibility).

**Comment by AndyHoggANU** [comment]
Could it be that the runoff is affecting the sea level? Surely not …

**Comment by russfiedler** [comment]
Could well be. Rule 1 of debugging these things. Check that your forcing fields as seen by the model are sane! Both from the ice side and the ocean side. Possibly try `ADJUST_NET_FRESH_WATER_TO_ZERO = TRUE` just to test quickly.

**Comment by angus-g** [comment]
Thanks @russfiedler! That's a very useful parameter indeed, I'd never heard of it. Setting that to true did indeed allow the run to start up just fine. Your musing was correct @AndyHoggANU, because there is no runoff, it's using the scaling factor, 1, as a constant value! So globally, the runoff was 1 kg/m2/s over the entire domain!

However, I've also just done the runoff regridding using https://github.com/adcroft/regrid_runoff, and the model runs fine with that as an input too:
```
python3 regrid_runoff.py hgrid_01.nc ocean_mask.nc -m mask RYF.runoff_all.1990_1991.nc -r friver eac_runoff.nc
ncatted -O -a cartesian_axis,i,a,c,X -a cartesian_axis,j,a,c,Y eac_runoff.nc
```
